apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auto-updater-operator
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: auto-updater-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auto-updater-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auto-updater-ui
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: auto-updater-ui
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auto-updater-ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auto-updater-parser
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: auto-updater-parser
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auto-updater-parser
