apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-updater-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auto-updater.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-updater-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auto-updater.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-updater-parser
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auto-updater.labels" . | nindent 4 }}
